### ISSUE TITLE
Please take into account slow network environments

### ISSUE THREAD

**Issue by mallibus** [AndreaPi/docker-training-2019-public#1]

**Comment by mallibus** [comment]
The training is very good, but when giving it with a 100Mbs bandwidth network or less, the download stages are very slow. Please provide an image with optio for using pre-trained weights

**Comment by AndreaPi** [comment]
Good suggestion! This is now fixed with 29fd0daac9faba68533af3074a0d2921a0174d2b. As explained in 5a5b04acca03d6f1dacb5909c3c79a7416da35b7, on slow Internet connections one can now overwrite the default `Dockerfile` with `Dockerfile.download.weights`, and all weights will be downloaded at build time.
